<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLdrBEOT\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLdrBEOT/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerLdrBEOT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerLdrBEOT\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerLdrBEOT\srcApp_KernelProdContainer([
    'container.build_hash' => 'LdrBEOT',
    'container.build_id' => 'a39c9abc',
    'container.build_time' => 1606918940,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLdrBEOT');
