<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5BufJTh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5BufJTh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5BufJTh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5BufJTh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container5BufJTh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '5BufJTh',
    'container.build_id' => '5154e123',
    'container.build_time' => 1607002604,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5BufJTh');
