<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIiUiUwB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIiUiUwB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIiUiUwB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIiUiUwB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIiUiUwB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IiUiUwB',
    'container.build_id' => '1be93af3',
    'container.build_time' => 1606921578,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIiUiUwB');
